### ISSUE TITLE
テスト

### ISSUE THREAD

**Issue by Yatty1** [Conon8901/Todo#1]

**Comment by Yatty1** [comment]
[practice.zip](https://github.com/Conon8901/Todo/files/1104807/practice.zip)

**Comment by Conon8901** [comment]
初回実行時
self.saveData.set(self.folderNameArray, forKey: "folder")
folderNameArray = saveData.object(forKey: "folder") as! [String]
にしてforKey: "folder"が確実にあるようにしなければならない

二回目以降
folderNameArray = saveData.object(forKey: "folder") as! [String]
self.saveData.set(self.folderNameArray, forKey: "folder")
前に保存したforKey: "folder"を呼び出さなければならない

ここのコードの違いはどうしたらいいでしょうか
